### ISSUE TITLE
NPEs when working with MP 4.0 features

### ISSUE THREAD

**Issue by yeekangc** [eclipse/lsp4mp#119] opened 2020-12-07 15:12 UTC
@Emily-Jiang reported the below when she was working with MP 4.0 APIs:

```
Caused by: java.lang.NullPointerException
	at org.eclipse.lsp4mp.extensions.reactivemessaging.MicroProfileReactiveMessagingItemMetadataProvider.getChannelInfo(MicroProfileReactiveMessagingItemMetadataProvider.java:323)
	at org.eclipse.lsp4mp.extensions.reactivemessaging.MicroProfileReactiveMessagingItemMetadataProvider.getConnectorChannelsAssociations(MicroProfileReactiveMessagingItemMetadataProvider.java:242)
	at org.eclipse.lsp4mp.extensions.reactivemessaging.MicroProfileReactiveMessagingItemMetadataProvider.doUpdate(MicroProfileReactiveMessagingItemMetadataProvider.java:201)
	at org.eclipse.lsp4mp.extensions.AbstractItemMetadataProvider.update(AbstractItemMetadataProvider.java:49)
	at org.eclipse.lsp4mp.extensions.ExtendedMicroProfileProjectInfo.synchUpdateCustomProperties(ExtendedMicroProfileProjectInfo.java:201)
	at org.eclipse.lsp4mp.extensions.ExtendedMicroProfileProjectInfo.updateCustomProperties(ExtendedMicroProfileProjectInfo.java:189)
	at org.eclipse.lsp4mp.services.MicroProfileLanguageService.updateProperties(MicroProfileLanguageService.java:248)
	at org.eclipse.lsp4mp.services.MicroProfileLanguageService.doCodeActions(MicroProfileLanguageService.java:228)
	at org.eclipse.lsp4mp.ls.ApplicationPropertiesTextDocumentService.lambda$codeAction$13(ApplicationPropertiesTextDocumentService.java:259)
	at org.eclipse.lsp4mp.ls.ApplicationPropertiesTextDocumentService$$Lambda$134/0000000041065E20.apply(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1236)
	... 7 more
[Error - 11:01:42 PM] Request textDocument/codeAction failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1238)
	at java.base/java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1205)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.NullPointerException
	at org.eclipse.lsp4mp.extensions.reactivemessaging.MicroProfileReactiveMessagingItemMetadataProvider.getChannelInfo(MicroProfileReactiveMessagingItemMetadataProvider.java:323)
	at org.eclipse.lsp4mp.extensions.reactivemessaging.MicroProfileReactiveMessagingItemMetadataProvider.getConnectorChannelsAssociations(MicroProfileReactiveMessagingItemMetadataProvider.java:242)
	at org.eclipse.lsp4mp.extensions.reactivemessaging.MicroProfileReactiveMessagingItemMetadataProvider.doUpdate(MicroProfileReactiveMessagingItemMetadataProvider.java:201)
	at org.eclipse.lsp4mp.extensions.AbstractItemMetadataProvider.update(AbstractItemMetadataProvider.java:49)
	at org.eclipse.lsp4mp.extensions.ExtendedMicroProfileProjectInfo.synchUpdateCustomProperties(ExtendedMicroProfileProjectInfo.java:201)
	at org.eclipse.lsp4mp.extensions.ExtendedMicroProfileProjectInfo.updateCustomProperties(ExtendedMicroProfileProjectInfo.java:189)
	at org.eclipse.lsp4mp.services.MicroProfileLanguageService.updateProperties(MicroProfileLanguageService.java:248)
	at org.eclipse.lsp4mp.services.MicroProfileLanguageService.doCodeActions(MicroProfileLanguageService.java:228)
	at org.eclipse.lsp4mp.ls.ApplicationPropertiesTextDocumentService.lambda$codeAction$13(ApplicationPropertiesTextDocumentService.java:259)
	at org.eclipse.lsp4mp.ls.ApplicationPropertiesTextDocumentService$$Lambda$134/0000000041065E20.apply(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1236)
	... 7 more
Dec 04, 2020 11:01:43 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.NullPointerException
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1238)
	at java.base/java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1205)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.NullPointerException
	at org.eclipse.lsp4mp.extensions.reactivemessaging.MicroProfileReactiveMessagingItemMetadataProvider.getChannelInfo(MicroProfileReactiveMessagingItemMetadataProvider.java:323)
	at org.eclipse.lsp4mp.extensions.reactivemessaging.MicroProfileReactiveMessagingItemMetadataProvider.getConnectorChannelsAssociations(MicroProfileReactiveMessagingItemMetadataProvider.java:242)
	at org.eclipse.lsp4mp.extensions.reactivemessaging.MicroProfileReactiveMessagingItemMetadataProvider.doUpdate(MicroProfileReactiveMessagingItemMetadataProvider.java:201)
	at org.eclipse.lsp4mp.extensions.AbstractItemMetadataProvider.update(AbstractItemMetadataProvider.java:49)
	at org.eclipse.lsp4mp.extensions.ExtendedMicroProfileProjectInfo.synchUpdateCustomProperties(ExtendedMicroProfileProjectInfo.java:201)
	at org.eclipse.lsp4mp.extensions.ExtendedMicroProfileProjectInfo.updateCustomProperties(ExtendedMicroProfileProjectInfo.java:189)
	at org.eclipse.lsp4mp.services.MicroProfileLanguageService.updateProperties(MicroProfileLanguageService.java:248)
	at org.eclipse.lsp4mp.services.MicroProfileLanguageService.doComplete(MicroProfileLanguageService.java:93)
	at org.eclipse.lsp4mp.ls.ApplicationPropertiesTextDocumentService.lambda$completion$1(ApplicationPropertiesTextDocumentService.java:168)
	at org.eclipse.lsp4mp.ls.ApplicationPropertiesTextDocumentService$$Lambda$130/000000005106BA20.apply(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1236)
	... 7 more
[Error - 11:01:43 PM] Request textDocument/completion failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1238)
	at java.base/java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1205)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.NullPointerException
	at org.eclipse.lsp4mp.extensions.reactivemessaging.MicroProfileReactiveMessagingItemMetadataProvider.getChannelInfo(MicroProfileReactiveMessagingItemMetadataProvider.java:323)
	at org.eclipse.lsp4mp.extensions.reactivemessaging.MicroProfileReactiveMessagingItemMetadataProvider.getConnectorChannelsAssociations(MicroProfileReactiveMessagingItemMetadataProvider.java:242)
	at org.eclipse.lsp4mp.extensions.reactivemessaging.MicroProfileReactiveMessagingItemMetadataProvider.doUpdate(MicroProfileReactiveMessagingItemMetadataProvider.java:201)
	at org.eclipse.lsp4mp.extensions.AbstractItemMetadataProvider.update(AbstractItemMetadataProvider.java:49)
	at org.eclipse.lsp4mp.extensions.ExtendedMicroProfileProjectInfo.synchUpdateCustomProperties(ExtendedMicroProfileProjectInfo.java:201)
	at org.eclipse.lsp4mp.extensions.ExtendedMicroProfileProjectInfo.updateCustomProperties(ExtendedMicroProfileProjectInfo.java:189)
	at org.eclipse.lsp4mp.services.MicroProfileLanguageService.updateProperties(MicroProfileLanguageService.java:248)
	at org.eclipse.lsp4mp.services.MicroProfileLanguageService.doComplete(MicroProfileLanguageService.java:93)
	at org.eclipse.lsp4mp.ls.ApplicationPropertiesTextDocumentService.lambda$completion$1(ApplicationPropertiesTextDocumentService.java:168)
	at org.eclipse.lsp4mp.ls.ApplicationPropertiesTextDocumentService$$Lambda$130/000000005106BA20.apply(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1236)
	... 7 more
```

**Comment by fbricon** [comment] 2020-12-07 15:15
can @Emily-Jiang attach a sample project reproducing the issue?

**Comment by angelozerr** [comment] 2020-12-07 16:42
According the stack trace it seems the `microprofile-config.properties` generate a property name which is null. I don't know how to reproduce it. 

The fix is easy (just to check if the property name is not null) but it should be very nice to write test for this issue.

@Emily-Jiang could you just share your `microprofile-config.properties` which cause this issue please. Thanks!

**Comment by Emily-Jiang** [comment] 2020-12-07 19:15
After restaring my vscode, I could not replicate this any more. Feel free to close this and I'll reopen when I get time to recreate this.

**Comment by yeekangc** [comment] 2020-12-07 20:26
Please re-open if the issue persists and can be re-created.  Thanks, Emily.

**Comment by fbricon** [comment] 2020-12-07 20:28
Let's keep it open until we at least add a null-check to the offending method

**Comment by angelozerr** [comment] 2020-12-08 10:20
After reading the parser code, I found a usecase:

Add in your properties file this line:

`%=1`

and everything is broken.

According to the code, the property name can be null when:

 * the property key is null (I think it's not possible to have that) -> https://github.com/eclipse/lsp4mp/blob/5c524bd5fa959724d4b31bfe061d025d62e7f423/microprofile.ls/org.eclipse.lsp4mp.ls/src/main/java/org/eclipse/lsp4mp/model/Property.java#L123
 * the property key defines % (which is for profile) without a '.'  -> https://github.com/eclipse/lsp4mp/blob/5c524bd5fa959724d4b31bfe061d025d62e7f423/microprofile.ls/org.eclipse.lsp4mp.ls/src/main/java/org/eclipse/lsp4mp/model/PropertyKey.java#L72

I think it's a bad idea that [Property#getPropertyName()](https://github.com/eclipse/lsp4mp/blob/5c524bd5fa959724d4b31bfe061d025d62e7f423/microprofile.ls/org.eclipse.lsp4mp.ls/src/main/java/org/eclipse/lsp4mp/model/Property.java#L120) can return null and it should return an empty string instead of null.  because:

 * We don't need this distinction (for the moment)
 * several code check if propertyName is equalled to something.

**Comment by angelozerr** [comment] 2020-12-08 10:39
Please see my PR https://github.com/eclipse/lsp4mp/pull/121 which will fix this bug.

**Comment by Emily-Jiang** [comment] 2020-12-08 21:15
Thank you @angelobanse for the inverstigation! I was a bit puzzled on why I hit the reactivemessaging code base as my microservices does not use Reactive Messaging at all. Do you know why?

**Comment by angelobanse** [comment] 2020-12-08 21:25
> Thank you @angelobanse for the inverstigation! I was a bit puzzled on why I hit the reactivemessaging code base as my microservices does not use Reactive Messaging at all. Do you know why?

I think you mean @angelozerr 😉

**Closed** 2020-12-09 08:00 UTC
Labels: bug

**Comment by angelozerr** [comment] 2020-12-09 08:23
> I was a bit puzzled on why I hit the reactivemessaging code base as my microservices does not use Reactive Messaging at all. Do you know why?

The reactivemessaging support is done by tracking some value of properties and properties are computed according to those value. See https://github.com/eclipse/lsp4mp/tree/master/microprofile.ls#managing-complex-properties for more explanation.

In other words, each time you type something, the reactivemessaging compute new properties according toe the value of some property (connector). But I agree with you, this support should be enabled only if the Java project is a reactivemessaging project.
