### ISSUE TITLE
Should not insert the whole proposed class code at the current cursor location

### ISSUE THREAD

**Issue by gkwan-ibm** [eclipse/lsp4mp#322] opened 2022-11-22 19:29 UTC
For the `mpnrc`, `mpliveness`, `mpreadiness`, or other proposals,  they should not simply insert the whole proposed class code to the file. It causes many complication errors. It should either replace the whole file or only propose when the file is empty. Similar as the `new_class` proposal in an empty file, press Ctrl+Space twice or three times to get following:

<img width="671" alt="Screen Shot 2022-11-21 at 2 53 19 PM" src="https://user-images.githubusercontent.com/29576299/203404347-88a5d36d-e4ad-4f81-b434-4d10341290a9.png">

**Comment by rgrunber** [comment] 2022-11-22 19:58
Seems similar to https://github.com/eclipse/lsp4mp/issues/108 .

**Comment by rgrunber** [comment] 2022-11-23 15:50
Closing this as a duplicate of #108 . We can prioritize that one. The difficult part will be that the snippets currently live in the MicroProfile LS, but that doesn't have access to the Java information (JDT) except through LS communication, which can be expensive. We would likely have to move the snippet registry / logic into the LSP4MP JDT component because it looks like snippet should be much smarter about when they apply.

**Closed by rgrunber** 2022-11-23 15:50 UTC
