### ISSUE TITLE
Filter out duplicate completion items coming from MP implementations

### ISSUE THREAD

**Issue by kathrynkodama** [eclipse/lsp4mp#48] opened 2020-08-12 12:35 UTC
When investigating #23, `smallrye-jwt` is contributing properties https://github.com/smallrye/smallrye-jwt/blob/319ec6b1e13dafeaa19e4f2a8e645107403795c5/implementation/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java#L108 for Thorntail projects. We want these `mp-jwt` properties to appear for all project types.
![image](https://user-images.githubusercontent.com/26146482/90014882-c0abf280-dc75-11ea-89fc-d059180fb64a.png)

The expected behaviour would be to manage the static properties with JSON and remove the duplicate `smallrye-jwt` properties.

We can filter out the duplicate properties in [MicroProfileCompletions.java](https://github.com/eclipse/lsp4mp/blob/master/microprofile.ls/org.eclipse.lsp4mp.ls/src/main/java/org/eclipse/lsp4mp/services/MicroProfileCompletions.java#L154) but it would be better if we filter them out when they are initially added to the properties list.

**Comment by angelozerr** [comment] 2020-08-12 12:42
> We can filter out the duplicate properties in MicroProfileCompletions.java 

I think we should do that.

> but it would be better if we filter them out when they are initially added to the properties list.

It was my first idea too, but it will not prevent from duplication with other external JDT extension which could provide duplication too.

@fbricon what do you think about that?

**Comment by fbricon** [comment] 2020-08-12 13:06
I don't understand where the duplicate is coming from. Can you provide a sample project? smallrye-jwt is not specific to Thorntail, or is it?

In general, the completion list should not contain duplicates. If the APIs use a Collection, backed by a LinkedHashSet, we should be fine, by I reckon I'm not familiar with the implementation details of the current codebase

**Comment by angelozerr** [comment] 2020-08-12 13:18
> I don't understand where the duplicate is coming from. 

The problem is that `smallrye-jwt` provides `mp.jwt.verify.publickey` with ConfigProperty annotation:

```java
@ConfigProperty(name = "mp.jwt.verify.publickey", defaultValue = NONE)
private Optional<String> mpJwtPublicKey;

```

See https://github.com/smallrye/smallrye-jwt/blob/319ec6b1e13dafeaa19e4f2a8e645107403795c5/implementation/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java#L108

Liberty doesn't provide this declaration, so there are no completion for `mp.jwt.verify.publickey` in this kind of project. To fix that, mp.jwt.verify.publickey must be declared in static with JSON, but if we do that, we will have duplication for project which will use `smallrye-jwt` .

I think thus duplication usecase can occur with other external JDT metadata provider, that's why I think filter should be done on MicroProfile LS side.

**Comment by fbricon** [comment] 2020-08-12 13:55
So how does OpenLiberty (or any other MP implem) handle mp.jwt.verify.publickey?

**Comment by kathrynkodama** [comment] 2020-08-12 15:07
> So how does OpenLiberty (or any other MP implem) handle mp.jwt.verify.publickey?

In Open Liberty the `mp.jwt.verify.publickey` property is not annotated with `ConfigProperty`

https://github.com/OpenLiberty/open-liberty/blob/c497890fabb500cec66d2beb2bcb1f9272e66184/dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/config/MpConfigUtil.java#L69-L72

**Comment by fbricon** [comment] 2020-08-12 15:21
Ok so handling duplicates is one thing, but providing completion for mp.jwt.* for all MP implementations just because OpenLiberty needs it seems wrong. That's something that should be contributed by an openliberty (akin to the quarkus one) specific extension IMHO. @yeekangc WDYT?

**Comment by rzgry** [comment] 2020-08-12 15:38
I think for Heldion the jwt properties would not be picked up since it looks like they dont use the ConfigProperty annotation either. https://github.com/oracle/helidon/blob/7d2f70897f4fb647539650b89d72cd042c26af91/microprofile/jwt-auth/src/main/java/io/helidon/microprofile/jwt/auth/JwtAuthProvider.java#L880

**Comment by kathrynkodama** [comment] 2020-08-25 13:22
@fbricon @angelozerr Since Open Liberty and Heldion do not annotate with ConfigProperty should we proceed with filtering out the duplicates?

**Comment by fbricon** [comment] 2020-09-10 07:40
we should make sure we never propose duplicates, no matter what

**Comment by angelozerr** [comment] 2020-09-10 14:16
At first as `mp.jwt.verify.publickey` is not managed by ConfigProperty for all MicroProfile Implementation, we need to add it with static JSON file description. If we do that, we have duplication of `mp.jwt.verify.publickey` with `smallrye-jwt`.

For me there are 2 kinds of duplication:

 * case 1: the duplication JSON+ConfigProperty explained below. 
 * case 2:  the duplication when several Java sources defines the same property name with ConfigProperty.

The case 1 and 2 should be handled differently:

 * case 1 : the duplication JSON+ConfigProperty should be managed on microprofile.jdt side. I mean when JSON descriptor must be merged we should check the existing of the property before adding it in 
https://github.com/eclipse/lsp4mp/blob/d1078b6b3f261003130e530dee9a9e512c19533a/microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/internal/core/PropertiesCollector.java#L99 To do that it requires that all JSON descriptor are merged after the other properties provider (from Java sources or classpath). In other words, we need to sort propertiesProvider here https://github.com/eclipse/lsp4mp/blob/55ac697e9382db279480d992a993f17bc7a92c60/microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/internal/core/PropertiesProviderRegistry.java#L112 by checking if properties provider implements AbstractStaticPropertiesProvider. In this case the provider must be added at the end, otherwise it can be inserted at first. If we do that, all tests should work.

 * case 2: I think we should create an another issue for that, because it's a new usecase. The idea is to filter the list on microprofile ls side. When definition is executed, it should work the 2 definitions of the duplicate property, for hover we should aggregate the content. perhaps it could be a good idea to higlight the error in the properties file to say that there are a duplicate property? But please create a new issue for that if you are agree with the case 1.

**Closed** 2020-09-18 08:01 UTC
